version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --omit=dev
  build:
    runtime-versions:
      nodejs: 20
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: no
